name: tropical_iptv_ios
description: Tropical IPTV iOS - Live TV, Movies and Series streaming app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  cached_network_image: ^3.4.1
  responsive_sizer: ^3.3.1
  awesome_snackbar_content: ^0.1.1
  google_fonts: ^6.2.1
  flutter_rating_bar: ^4.0.1
  readmore: ^3.0.0
  filling_slider: ^0.0.3
  loading_animation_widget: ^1.3.0

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get: ^4.6.6
  
  # Storage
  get_storage: ^2.1.1
  
  # Utils
  intl: ^0.19.0
  url_launcher: ^6.3.1
  volume_controller: ^2.0.7
  screen_brightness: ^1.0.1

  # Video Players
  flutter_vlc_player: ^7.4.3
  pod_player: ^0.2.2

  # HTTP
  dio: ^5.8.0

  # Ads (optional)
  google_mobile_ads: ^5.3.1

  # Firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
