// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRoGZQZD7k-18-BmLq7X4QMGJ5ODJwemc',
    appId: '1:427954135204:web:9af896d2534d1817950631',
    messagingSenderId: '427954135204',
    projectId: 'iptv-black',
    authDomain: 'iptv-black.firebaseapp.com',
    databaseURL: 'https://iptv-black-default-rtdb.firebaseio.com',
    storageBucket: 'iptv-black.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBra3jFXX5NSWjptFggZa9qWIoK7isQJxM',
    appId: '1:427954135204:ios:40c7cd35dae8a7c0950631',
    messagingSenderId: '427954135204',
    projectId: 'iptv-black',
    storageBucket: 'iptv-black.firebasestorage.app',
    databaseURL: 'https://iptv-black-default-rtdb.firebaseio.com',
    iosBundleId: 'com.tropical.play',
  );
}
